### ISSUE TITLE
Downsampling according to the library size

### ISSUE THREAD

**Issue by lihm1** [parklab/SigMA#43]
Hi,
I am interested in the downsampling method in your paper, but I do not know how to downsamped to get wes or panel data from wgs according to the library of the sequencing platform, can you give me more information about this.

**Comment by dgulhan-bio** [comment]
I did this by determining the mutations that fall into panel coverage. Due to differences in WGS data read depth and panel read depth I then add additional mutations per sample using the remaining mutations on other genes not included in the panel. How many additional mutations should be added is determined using the average mutation count in the simulation and real data. I cannot make the simulation part of the code public because WGS data I used requires access to be granted and I cannot make the WGS data public. I used WGS data from ICGC consortium. I hope this helps.
